### ISSUE TITLE
Run it with python

### ISSUE THREAD

**Issue by Dado87** [mojocorp/geodesic#4]
Hi,
Can I ask you for some support running the code from python 2.7 on Windows 10?
After opening it in cmake and trying to configure it I get following problem:

Looking for pthread.h
Looking for pthread.h - not found
Found Threads: TRUE

Regards,
Dado

**Comment by mojocorp** [comment]
What is the problem ?

**Comment by Dado87** [comment]
Sorry, it was just my inexperience with cmake... it worked just well afterwards. No Issue.
